myfrontend/src/pages/login/index.js, myfrontend/src/pages/login/styles.css, myfrontend/src/routes.js
Foi integrado o login e suas verificações
=> 83 fazer integração do login

myfrontend/package-lock.json, myfrontend/package.json, myfrontend/src/pages/edit-profile/index.js, myfrontend/src/pages/edit-profile/styles.css
Este é um Pull Request com as alterações propostas anteriormente na issue #85 que foi desenvolvida por Lucas Firmo. Esta branch teve seu merge dado com a branch main de forma equivocada.
Foi adicionado campos que permitem a edição do usuário, são eles os inputs: campo de nome (alterar nome), campo de username (para alterar o username) e o campo de bio (para alterar algo sobre o usuário). Por fim um botão para concluir a alteração dos dados.
Ele também acompanha o componente menu.
=> feat: adiciona tela de edicao do perfil do usuario

myapi/myapi/settings.py, myfrontend/src/api.js, myfrontend/src/components/menu/index.js, myfrontend/src/pages/login/index.js
Foram implementadas algumas melhorias no sistema, incluindo a integração do recurso de logout. Agora, é possível sair da sessão selecionando a opção correspondente no menu, como ilustrado na imagem.
Além disso, foi adicionada uma verificação para o caso em que o token de autenticação expirou. Quando isso ocorre, o sistema realiza uma requisição à API para obter um novo token, utilizando o refresh_token. A imagem apresenta um exemplo de como essa verificação é feita e como é requisitado um novo token.
=> feat: adicionando integracao do logout e renovacao de token

myfrontend/src/components/Publication/styles.css, myfrontend/src/pages/home/styles.css
Foi consertado um bug que altarava a cor dos botões do componente Pagination.
=> fix: resolvendo bug de cores dos numeros do componente Pagination

myfrontend/src/components/SuperCritico/index.js, myfrontend/src/components/SuperCritico/styles.css, myfrontend/src/pages/profile/index.js, myfrontend/src/pages/profile/styles.css
Foi adicionando um componente no qual pode ser reutilizado em qualquer lugar para indicar que o usuário é um supercritico.
Sendo possível ser utilizado em qualquer lugar
=> feat: adicionando selo de supercritico

myfrontend/src/pages/user/index.js, myfrontend/src/routes.js
Foi adicionado a pagina que permite visualizar o perfil de outro usuário.
Ainda é necessário adicionar o botão de Seguir e Desseguir, que ainda precisa ser inserida.
Visitando o próprio perfil com a tela criada
Visitando o perfil de outro usuário com a tela criada
=> feat: Adicionando perfis de outros usuarios

myapi/usuarios/views.py, myfrontend/src/components/Publication/index.js, myfrontend/src/components/Publication/styles.css
Este Pull Request resolve a issue #128 e inclui as seguintes mudanças:
A integração para o upload de imagens foi concluída, permitindo agora a inserção de imagens nas publicações. Foi adicionado um indicador de carregamento para lidar com a demora no processamento da imagem pelo backend, e um ícone de confirmação foi incluído ao finalizar a publicação.
=> 128 fazer integracao para upload das imagens na publicacao

myapi/usuarios/tests.py, myapi/usuarios/urls.py, myapi/usuarios/views.py
Olá, gostaria de submeter este pull request para análise. Entretanto, este pull request depende do pull request #150 , o qual ainda não foi aceito.
Embora as mudanças propostas aqui sejam independentes das mudanças propostas no pull request #150, é importante que a funcionalidade de adicionar e remover os filmes favoritos seja aceita e integrada ao código base antes da funcionalidade de listagem.
Este Pull Request resolve a issue #52 e inclui as seguintes mudanças:
Foi introduzida a funcionalidade de listagem de filmes favoritos.
Por fim, foram introduzidos testes para garantir que a funcionalidade esteja funcionando corretamente.
=> 52 criar back end que permita retornar uma lista de filmes favoritados

myfrontend/src/components/menu/index.js, myfrontend/src/index.css, myfrontend/src/pages/login/index.js, myfrontend/src/pages/sign-up/index.js, myfrontend/src/pages/sign-up/styles.css
Foi alterado as cores das telas iniciais que se diferenciavam muito do restante da aplicação.
Também foi definido as cores por meio de variáveis no css. Espera-se que essas variáveis sejam utilizadas de agora em diante para manterem um padrão da aplicação.
=> fix: altera cores que nao condizem com o restante da aplicacao

myfrontend/src/pages/favoritos/index.js, myfrontend/src/pages/favoritos/styles.css, myfrontend/src/pages/profile/index.js, myfrontend/src/routes.js
Foi criado um botão no /profile chamado favoritos que leva a pagina de listagem dos filmes favoritos
Foi criado também a pagina de listar os favoritos, com 4 exemplos de filmes que estão feitos de forma estática, o botão de desfavoritar tira o filme da lista, porém ao atualizar a pagina as modificações são ignoradas já que foram feitas de forma estática
=> Feat: listar favoritos

myfrontend/src/components/CardFollower/index.js, myfrontend/src/components/CardFollower/styles.css, myfrontend/src/pages/edit-profile/styles.css, myfrontend/src/pages/home/styles.css, myfrontend/src/pages/profile/index.js, myfrontend/src/pages/profile/styles.css
Este Pull Request resolve a issue #63 e inclui as seguintes mudanças:
Quando selecionado a opção Seguidores ou Seguindo, a seguinte tela é exibida.
Esta tela faz a listagem de todos os seguidores, com a opção de seguir e deixar de seguir. Espera-se com a integração na issue #131 , se encaminhar para o perfil do usuário quando ele for selecionado.
=> 63 criar front end na tela de perfil do usuario que exiba a lista de todos os usuarios que um determinado usuario e seguido

myfrontend/src/components/header/index.js, myfrontend/src/components/header/styles.css, myfrontend/src/pages/search/index.js
Primeiramente foi adicionado dois radio para selecionar que tipo de pesquisa o usuário quer fazer
Selecionando a opção usuário para fazer a pesquisa
Depois foi inserido paginações diferentes, caso ele selecione o usuário para pesquisar, ele irá pesquisar o usuário
=> feat: Adicionando pesquisa de usuario na header e na pagina de pesquisa

myfrontend/src/pages/following/index.js
Este Pull Request resolve a issue #160 e inclui as seguintes mudanças:
Foi criado uma tela "following". Essa tela apresenta os usuários que o usuário logado segue. A implementação com o frontend da tela "followers" é bem semelhante. Dessa forma, foram utilizados alguns componentes semelhantes que podem ter seus nomes alterados no futuro para algo mais genérico.
=> feat: adiciona frontend da tela com os usuarios que o usuario segue

myapi/usuarios/views.py, myfrontend/src/components/CardFollower/index.js, myfrontend/src/components/menu/index.js, myfrontend/src/pages/favoritos/index.js, myfrontend/src/pages/followers/index.js, myfrontend/src/pages/following/index.js, myfrontend/src/pages/profile/index.js
Este Pull Request resolve a issue #130 e inclui as seguintes mudanças:
Foi realizado a integração para a listagem dos usuarios seguidores e dos usuarios que o usuario segue. 
Também foi integrado as funcionalidades de seguir e desseguir.
=> 130 fazer integracao para listar os usuarios que um usuario segue

myapi/usuarios/urls.py, myapi/usuarios/views.py, myfrontend/src/pages/movie/index.js
Olá, gostaria de submeter este pull request para análise. Entretanto, este pull request depende do pull request #159 o qual ainda não foi aceito.
Embora as mudanças propostas aqui sejam independentes das mudanças propostas no pull request #159, é importante que as funcionalidades de frontend de favoritar/desfavoritar sejam aceitas e integradas ao código base antes.
Este Pull Request resolve a issue #151 e inclui as seguintes mudanças:
Foi adicionado a integração da tela de favoritos. Agora é possível favoritar um filme e consequentemente vê-los na tela de favoritos.
Também foi criado uma rota no backend para verificar se o filme foi favoritado. Essa rota retorna true ou false.
=> 151 fazer integracao ao favoritar um filme

myapi/usuarios/tests.py, myapi/usuarios/urls.py, myapi/usuarios/views.py
Este Pull Request resolve a issue #177 e inclui as seguintes mudanças:
Foi adicionado a funcionalidade de retornar as publicacoes de um usuario pelo id. Além disso, esse retorno está sendo feito com paginação de 20 publicacoes por página.
=> 177 criar backend para listar publicacoes de um usuario especifico

myfrontend/src/components/ViewPublication/index.js, myfrontend/src/pages/home/index.js, myfrontend/src/pages/profile/index.js
Foi adicionando a integração da publicação na tela do usuário (/profile) e colocando as opções de publicação apenas para o usuário.
/profile
Home (com outros usuários)
=> feat:fix: adicionando publicacao no perfil do usuario e ajustando opcoes de publicacao

myfrontend/src/components/menu/styles.css, myfrontend/src/pages/home/styles.css, myfrontend/src/pages/profile/styles.css
Este Pull Request resolve a issue #193.
Foi consertado o design do fundo das publicações.
=> fix: conserta design do fundo das publicacoes

myfrontend/src/components/header/index.js, myfrontend/src/components/headerDesktop/index.js
Este Pull Request resolve a issue de número #192.
Foi adicionar a troca do texto do placeholder ao pesquisar um usuário.
=> fix: conserta texto do placeholder ao pesquisar um usuario

myfrontend/src/components/ViewPublication/index.js, myfrontend/src/components/ViewPublication/styles.css
Foi adicionado o campo embaixo de cada critica que possibilita o comentário
E por sua vez, também ver a listagem dos comentários publicados na critica
=> feat: adicionando frontend dos comentarios

myfrontend/src/components/ViewPublication/index.js, myfrontend/src/components/ViewPublication/styles.css
Foi adicionado um botão de curtir e descurtir, com interação
=> feat: adicionando botao de curtir e descurtir critica

myfrontend/src/components/movieFilter/styles.css, myfrontend/src/pages/edit-profile/index.js, myfrontend/src/pages/edit-profile/styles.css
Este Pull Request resolve a issue #203.
Foi adicionado um campo que permite a adição de fotos para o perfil do usuário.
=> feat: adiciona campo para adicao de imagem de perfil

myfrontend/src/pages/favoritosUsers/index.js, myfrontend/src/pages/user/index.js, myfrontend/src/routes.js
Este Pull Request resolve a issue #230
Foi realizado a implementação da tela de favoritos de outros usuários e acrescentado uma opção que permite acessar essa tela.
=> feat: adiciona frontend da listagem dos favoritos de outros usuarios

myfrontend/src/pages/movie/index.js
Este Pull Request resolve a issue #217.
Foi adicionado a integração para adicionar e remover filmes da watchlist. Agora é possível adicionar filmes na watchlist que serão posteriormente listados na issue #198 e #226.
=> feat: adiciona integracao para colocar filmes na watchlist

myfrontend/src/pages/movie/index.js, myfrontend/src/pages/watchlist/index.js, myfrontend/src/pages/watchlist/styles.css
Primeiramente, é importante ressaltar que o pull request #214 depende do pull request #217 que propõe a integração da watchlist e permite adicionar filmes na watchlist. Dessa forma, é importante que o pull request #217 seja revisado e integrado a branch de desenvolvimento antes da funcionalidade apresentada nesse pull request.
Este Pull Request resolve a issue #214.
Foi realizado a integração da funcionalidade da listagem dos filmes da watchlist. Agora, é exibido os filmes da watchlist do usuário e é possível removê-los e coloca-los de volta na watchlist. Também foi incluso a paginação na listagem da watchlist.
=> 214 fazer integracao da listagem da watchlist

myapi/usuarios/views.py, myfrontend/src/pages/favoritos/index.js, myfrontend/src/pages/favoritos/styles.css, myfrontend/src/pages/favoritosUsers/index.js, myfrontend/src/pages/favoritosUsers/styles.css, myfrontend/src/pages/user/index.js, myfrontend/src/routes.js
É importante ressaltar que este pull request depende das alterações propostas no pull request #269. É necessário que o Pull Request #269 seja aceito e integrado a branch de desenvolvimento antes que este pull request seja aceito.
Este Pull Request resolve a issue #232.
Foi adicionado a tela de favoritos de outros usuários. Nessa tela, além de visualizar os filmes favoritos, é possível favoritar e desfavoritar os filmes. Por fim, também foi incluso paginação com a exibição de 20 filmes por página.
=> 232 fazer integracao para listagem dos filmes favoritos de outros usuarios

myapi/usuarios/serializers.py, myapi/usuarios/urls.py, myapi/usuarios/views.py, myfrontend/src/components/CardNotification/index.js, myfrontend/src/components/CardNotification/styles.css, myfrontend/src/components/FragmentDetailsNotification/index.js, myfrontend/src/components/FragmentDetailsNotification/styles.css, myfrontend/src/components/ViewPublication/index.js, myfrontend/src/components/header/index.js, myfrontend/src/components/header/styles.css, myfrontend/src/components/headerDesktop/index.js, myfrontend/src/components/headerDesktop/styles.css, myfrontend/src/pages/home/index.js, myfrontend/src/pages/movie/styles.css, myfrontend/src/pages/notifications/index.js, myfrontend/src/pages/notifications/styles.css, myfrontend/src/pages/publication/index.js, myfrontend/src/pages/user/index.js, myfrontend/src/routes.js
Este Pull Request resolve a issue #244.
Foi realizado a integração das notificações. Agora é exibido o número de notificações e as notificações do usuário. Além de ser exibido se ela já foi lida ou não. Caso tenha mais do que 10 notificações não lida o número será de 10+.
Além disso, é possível ver a página das notificações, onde são exibidas detalhadamente e com paginação.
=> 244 fazer integracao das notificacoes 2

myfrontend/src/components/headerDesktop/index.js
Este Pull Request resolve a issue #292.
Na função notificationNow foi pego o estado atualizado para o botão de ver mais. Agora, ele não desaparece repentinamente.
=> fix: conserta botao que desaparece

myfrontend/src/pages/publication/index.js
Este Pull Request resolve a issue #294.
Foi alterado o id da publicação para o componente da publicação. Antes estava sendo enviado a data e não o id.
=> fix: conserta erro do like e deslike na pagina da publicacao

myapi/usuarios/models.py, myfrontend/src/pages/favoritosUsers/index.js, myfrontend/src/pages/user/index.js, myfrontend/src/pages/watchlist/index.js, myfrontend/src/routes.js
Este Pull Request resolve a issue #298 
Foi criado um campo date no backend para a lista de filmes favoritos.
=> fix: resolve bug da listagem dos favoritos de outros usuarios

myfrontend/src/components/FragmentDetailsNotification/index.js, myfrontend/src/pages/publication/index.js
Este Pull Request resolve a issue #294.
Foi arrumado o bug de retorno das notificações em que ficava travado. Agora, quando aberto uma notificação e retornado a página é retornada da fato.
=> fix: arruma bug do retorno das notificacoes

myfrontend/src/pages/movie/index.js
Este Pull Request resolve a issue #289 
Foi alterado a rota de recomendações de similares. Agora, as recomendações de filmes são mais consistentes.
=> feat: adiciona rota de recomendacoes

myfrontend/src/components/header/index.js
Este Pull Request resolve a issue #304.
Foi consertado o bug que exibia de forma errada a mensagem de "não há notificações"
=> fix: conserta bug ao nao existir notificacoes

myfrontend/src/pages/profile/index.js
Este Pull Request resolve a issue #302.
Foi arrumado o retorno para a tela do perfil.
=> fix: arruma bug de retorno para a tela de perfil

myfrontend/src/pages/sign-up/index.js
Foi ajustado campos de signup, no qual mostra erros ao mesmo tempo, não possibilitando deste modo datas futuras.
=> feat: ajustando e mostrando erros do signup
